import numpy as np
import sys
import time

s=100000
l1=range(s)
l2=range(s)
st=time.time()

r=[(x+y) for x,y in zip(l1,l2)]
print("python list : ",(time.time()-st)*1000)

a1=np.arange(s)
a2=np.arange(s)
st=time.time()
r=a1+a2
print("Numpy is :",(time.time()-st)*1000)
import numpy as np
a=np.array([[[1,2,3],[7,4,8]],[[13,4,68],[4,5,7]]])
print("Array :\n",a)
print("Dimensions: \n",a.ndim)
print("Shape:\n",a.shape)
print("Size:\n",a.size)
print("Data type:\n",a.dtype)
print("Zeros:\n",np.zeros((2,3)))
print("Ones:\n",np.ones((2,2)))
print("Full:\n",np.full((4,3),8))
print("Identity Matrix: \n",np.eye(6))
print("Range:\n",np.arange(1,10,2))
print("Even spacing:\n",np.linspace(1,20,6))
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print("Element wise operations multiplication :\n",a*b)
print("Element wise operations addition :\n",a+b)
print("Element wise operations subtraction :\n",a-b)
print("Element wise operations module :\n",a%b)
print("Element wise operations division :\n",a/b)
print("Scalar operations:\n",a*2)
print("Scalar operations:\n",b*3)
a=np.array([24,67,23,82,79,24,90])
print("Array: ",a)
print("Statistical Sum:\n",np.sum(a))
print("Statistical Max:\n",np.max(a))
print("Statistical Min:\n",np.min(a))
print("Statistical Mean:\n",np.mean(a))
print("Statistical Std:\n",np.std(a))
a=np.array([[1,3,6,8],[42,6,8,2]])
print("Column-wise sum: \n",np.sum(a,axis=0))
print("Row-wise  Sum:\n",np.sum(a,axis=1))
a=np.array([[1,3,6,8],[42,6,8,2]])
b=np.array([10,40,60,80])
print("Broadcasting addition: \n",a+b)
print("Broadcasting multiplication: \n",a*b)
print("Broadcasting subtraction: \n",a-b)
print("Broadcasting module: \n",a%b)
print("Broadcasting division: \n",a/b)
print("Broadcasting Scalar operations: \n",a*2)
print("Broadcasting Scalar operations: \n",b*3)
a=np.array([2,9,4,5])
b=a.copy()
b[2]=304
print(a)
print("Copy view array: \n",b)
print("Random numbers array:",np.random.rand(3,3))
print("Random numbers array:",np.random.randint(1,10,(3,3)))
a=np.array([8,492,4813,4,775,1,9])
print("Sorting :\n",np.sort(a))
a=np.array([23,494,39,3,28,53,40])
print("Boolean making :\n",a[a>35])